server:
  port: 9999
  error:
    include-message: always

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: spring-security-jwt
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?createDatabaseIfNotExist=true
    username: root
    password: 0003pray
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem

logging:
  level:
    org:
      springframework: INFO


